# -*- coding: utf-8 -*-
"""Final05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7KIGZte8tMuVAskGJK681DykHwbG7lU
"""

name = input("บอกชื่อของคุณครับ")
print("\nสวัสดีคุณ  ", name, "ครับ")
print("โปรแกรมนี้คือ โปรแกรมเปลี่ยนองศาเป็นค่า ฟาเรนไฮท์ และ ค่าเคลวินครับ")

celsius = float(input("\nใส่ค่าองศาของคุณ (เซลเซียส): "))
fahrenheit = (celsius * 9/5) + 32
kelvin = (celsius + 273.15)
print(f"อุณหภูมิ ฟาเรนไฮต์ เท่ากับ {fahrenheit}")
print(f"อุณหภูมิ เคลวิน เท่ากับ {kelvin}")

print("โปรแกรมจัดทำโดย 05 Tutor Nataphont")